### ISSUE TITLE
Bird names in other language?

### ISSUE THREAD

**Issue by PATROMO** [jhansche/pybirdbuddy#13]
Is it possible and if so how to get the birds names in German or another language?

**Comment by jhansche** [comment]
I've just confirmed that if I send the `Accept-Language: de` header, I get back bird species information in the requested language.

I'll add support for that in the BirdBuddy client, to allow setting the preferred language code.

**Comment by jhansche** [comment]
This feature will be available in the HA integration in v0.0.15, not yet released.
