### ISSUE TITLE
Using finish_postcard()

### ISSUE THREAD

**Issue by DenchyRS** [jhansche/pybirdbuddy#17]
I have some code I am working on and want it to push the postcard into collections to clear up the postcard feed. However I can't seem to get finish_postcard() to work. I get the error that it is missing 1 required positional argument 'sighting_result' and I understand it is missing, but after looking through the code and trying a few different things I can't seem to find the right solution. 

I apologies again to bother you, but I just wish to learn!

```
        getPostcards = await bb.new_postcards()
        getSightings = await bb.sighting_from_postcard(getPostcards[0])
        
        await bb.finish_postcard(getSightings, ????)
```
        
It seems to be correctly getting the postcards and I believe converting them to sightings, as I can pull images from them etc. I just have no I dead what the secibd argument for finish_postcard() would be.

Thanks.

**Comment by jhansche** [comment]
[`finish_postcard`](https://github.com/jhansche/pybirdbuddy/blob/c56ccdb2ee7ffb1eb6780ddeca10bc35d9074eab/birdbuddy/client.py#L387) needs both the postcard id (the feed item id) and the converted sighting data, as PostcardSighting. See how it's used in the Home Assistant component [here](https://github.com/jhansche/ha-birdbuddy/blob/fd6055c73b985fe6b9ba2bc4d69cfa62aeacff19/custom_components/birdbuddy/coordinator.py#L90), and [here](https://github.com/jhansche/ha-birdbuddy/blob/fd6055c73b985fe6b9ba2bc4d69cfa62aeacff19/custom_components/birdbuddy/coordinator.py#L130).

In your example, the postcard is `getPostcards[0]`, which has an item 'id', and sighting report is `getSightings`, so the correct line would be:
```
await bb.finish_postcard(getPostcards[0]['id'], getSightings)
```

**Comment by DenchyRS** [comment]
Oh thank you very much that solved it!

Appreciate the help and I will defo take a look at your Home Assistant stuff to see if it can answer my questions in the future!
